### ISSUE TITLE
Dynamic images

### ISSUE THREAD

**Issue by jakewhiteley-gc** [snapwp/snap-core#39]

**Comment by jakewhiteley** [comment]
Left to do:

// ADD GENERATED SIZE INFO TO MEDIA ADMIN?
// MAKE SURE WORKS WITH GC STUFF, S3, EWWW, REGENERATE THUMBNAILS
// MAYBE KILL ALL DEFAULT SIZES APART FROM FULL/THUMB TO CATCH WC AS WELL
// ADD OPTION FOR PICTURE ELEMENT OUTPUT
// ADD WAY OF DEFINING 2XDPI IMAGES ETC
// FIX SRCSET TO NOT SUCK

 //unset($meta['sizes']);
 //wp_update_attachment_metadata($id, $meta);
